spring:
  application:
    admin: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/fishmanwang/RUM
            searchPaths: config
            label: master
            username:
            password:
